language: r
sudo: false
cache: packages

after_success:
  - Rscript -e 'covr::codecov()'

env:
  global:
  - R_BUILD_ARGS=" "
  - R_CHECK_ARGS="--as-cran"
  - BOOTSTRAP_LATEX="1"

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: TVe5SE4SzZ87hhfBVKpkumT5H4IDXLjP/YsyJs1sNeDk6GOy1LDHiMofRhGJMKuqkU2CUCPqMpGbQy3gZD8hUIIQDHniKcaQwULIE1NqIzCKEoWmkhHFiARdhQA2+ZTAEzpYUthKWD8nDPfc2MIiv7zeqEwg2oIat4Wrd92iPic=
